# Generated by Django 4.0.5 on 2022-06-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('ini-cog', 'Engrenagem'), ('ini-stats-up', 'Gráfico'), ('ini-users', 'Usuários'), ('ini-layers', 'Design'), ('ini-mobile', 'Mobile'), ('ini-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='servico',
            field=models.CharField(max_length=100, verbose_name='Serviço'),
        ),
    ]
